## Travis CI configuration.
##
##   <https://travis-ci.org/mdklatt/cookiecutter-www-static>
##
language: node_js

branches:
  only:
    - master
    - dev

sudo: false

install:
  # Because this is a Node.js project Travis does not create a Python venv,
  # so pip needs to install packages locally.
  - pyenv versions
  - pyenv local 3.6
  - python -m pip install --requirement=requirements.txt --user

script:
  - python tests/test_template.py
